### ISSUE TITLE
breaking send to conemu/cmder in windows anniversary

### ISSUE THREAD

**Issue by mataddy** [randy3k/SendREPL#10]
first, thanks for this and sendtextplus; both saved my workflow when making the move to windows.

everything has worked great until I upgraded to the anniversary windows 10, at which point a clean install of sublime build 3114 (release) or 3120 (latest) plus package controller fail to send text to either cmder or conemu of a variety of versions.  The error is 

```
Traceback (most recent call last):
  File "./python3.3/subprocess.py", line 1104, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 798, in run_
    return self.run(edit)
  File "C:\Users\taddy\AppData\Roaming\Sublime Text 3\Packages\SendREPL\send_repl.py", line 67, in run
    sender.send_text(cmd)
  File "C:\Users\taddy\AppData\Roaming\Sublime Text 3\Packages\SendREPL\text_sender.py", line 74, in send_text
    self.send_to_conemu(cmd)
  File "C:\Users\taddy\AppData\Roaming\Sublime Text 3\Packages\SendREPL\text_sender.py", line 46, in send_to_conemu
    send_to_conemu(cmd, self.bracketed_paste_mode)
  File "C:\Users\taddy\AppData\Roaming\Sublime Text 3\Packages\SendREPL\conemu\__init__.py", line 51, in send_to_conemu
    ret = subprocess.call("ConEmuC /ConInfo", startupinfo=startupinfo)
  File "./python3.3/subprocess.py", line 523, in call
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1110, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

```

but note that from cmder conemuc /coninfo works no problem:

```
λ ConEmuC /ConInfo
ConEmu 160710 x86
OS Version: 10.0.14393 (2:)
SM_IMMENABLED=1, SM_DBCSENABLED=0, ACP=1252, OEMCP=437
ConHWND=0x003B0252, Class="ConsoleWindowClass"
Console font info: 0, {3x5}, 54, 400, "Lucida Console"
Handles: In=x8 (Mode=x1F7) Out=xC (x3) Err=x10 (x3)
Buffer={80,1000} Window={0,0}-{79,38} MaxSize={80,131}
Cursor: Pos={0,9} Size=25% Visible
ConsoleCP=437, ConsoleOutputCP=437
CP437: Max=1 Def=x3F,x00 UDef=x3F
  Lead=x00,x00,x00,x00,x00,x00,x00,x00,x00,x00,x00,x00
  Name="437   (OEM - United States)"
```

happy to be told that this is user error, any help is very welcome.

**Comment by randy3k** [comment]
Try adding the path to ComEmuC.exe to the PATH variable, it should fix it.

**Comment by mataddy** [comment]
many thanks.  It was already in there but your comment made me realize I was pointing to the wrong comemuc.  Instead of the separate conemu install, which is also on my machine, I needed the one included inside cmder, at cmder\vendor\conemu-maximus5\ConEmu.  duh.  thanks!!
