### ISSUE TITLE
conemu no longer workign

### ISSUE THREAD

**Issue by musm** [randy3k/SendREPL#20]
For some reason SendREPL is no longer working for me

I checked and yes ConEmuC is in path.

Thanks

```
Package Control: Skipping automatic upgrade, last run at 2016-12-10 22:08:00, next run at 2016-12-10 23:08:00 or after
ConEmuC.exe not found. Edit PATH variable and add path to ConEmuC.exe.
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "C:\Users\Mus\AppData\Roaming\Sublime Text 3\Packages\SendREPL\send_repl.py", line 67, in run
    sender.send_text(cmd)
  File "C:\Users\Mus\AppData\Roaming\Sublime Text 3\Packages\SendREPL\text_sender.py", line 81, in send_text
    self.send_to_conemu(cmd)
  File "C:\Users\Mus\AppData\Roaming\Sublime Text 3\Packages\SendREPL\text_sender.py", line 47, in send_to_conemu
    send_to_conemu(cmd, conemuc, self.bracketed_paste_mode)
  File "C:\Users\Mus\AppData\Roaming\Sublime Text 3\Packages\SendREPL\conemu\__init__.py", line 66, in send_to_conemu
    _send_to_conemu(cmd, conemuc, bracketed)
  File "C:\Users\Mus\AppData\Roaming\Sublime Text 3\Packages\SendREPL\conemu\__init__.py", line 86, in _send_to_conemu
    '{}} -GuiMacro:0 Paste(2,"\x1b[200~{}\x1b[201~")'.format(conemuc, escape_dquote(cmd)),
ValueError: Single '}' encountered in format string
```

**Comment by randy3k** [comment]
Would you try specifying the path to `ConEmuC.exe` in the settings?

**Comment by randy3k** [comment]
By the way, there are several bugs related to ConEmu in 0.1.9, please update to 0.1.10.

**Comment by musm** [comment]
```
{
	"prog": "conemu",

	"conemuc": "C:\\Program Files\\ConEmu\\ConEmu\\ConEmuC.exe"


}

```
is in my SendREPL.sublimte-settings

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "C:\Users\Mus\AppData\Roaming\Sublime Text 3\Packages\SendREPL\send_repl.py", line 67, in run
    sender.send_text(cmd)
  File "C:\Users\Mus\AppData\Roaming\Sublime Text 3\Packages\SendREPL\text_sender.py", line 81, in send_text
    self.send_to_conemu(cmd)
  File "C:\Users\Mus\AppData\Roaming\Sublime Text 3\Packages\SendREPL\text_sender.py", line 47, in send_to_conemu
    send_to_conemu(cmd, conemuc, self.bracketed_paste_mode)
  File "C:\Users\Mus\AppData\Roaming\Sublime Text 3\Packages\SendREPL\conemu\__init__.py", line 66, in send_to_conemu
    _send_to_conemu(cmd, conemuc, bracketed)
  File "C:\Users\Mus\AppData\Roaming\Sublime Text 3\Packages\SendREPL\conemu\__init__.py", line 88, in _send_to_conemu
    '{}} -GuiMacro:0 Paste(2,"\x1b[200~{}\x1b[201~")'.format(conemuc, escape_dquote(cmd)),
ValueError: Single '}' encountered in format string

```

I have the latest ConEmu version 161206

**Comment by musm** [comment]
if this helps:
![image](https://cloud.githubusercontent.com/assets/4319522/21082770/291b0da6-bfb0-11e6-9e88-ecfda079ac3c.png)

**Comment by randy3k** [comment]
I finally figured it out, it was because of an extra brace https://github.com/randy3k/SendREPL/commit/4b93939644b1e3cdf2c0494b1e504e7ca766dfe3.
Fixed in 0.1.11.

**Comment by musm** [comment]
Thank you! I can't live without this plugin !!

**Comment by musm** [comment]
How long does it take to show up in package manager?

**Comment by randy3k** [comment]
By the way, it should have no problem if you turn off the bracket paste model. For you information, it is only turn on by default for Julia language.

**Comment by musm** [comment]
I'm not really sure what bracket paste mode is or does . I use this plugin for Julia. Is there something I should do / check?

**Comment by randy3k** [comment]
Bracket paste mode allows console to read text with multiple line breaks and special characters which is not possible otherwise. Julia and IPython (>5.0.0) both support BPM.

Btw, does the new version fix your issue?

**Comment by musm** [comment]
Yes thanks for the prompt reply and package
