### ISSUE TITLE
Error sending text on OSX

### ISSUE THREAD

**Issue by andrewrech** [randy3k/SendREPL#4]
When attempting to send `print("test")` to R running in iTerm, I get the following error in iterm.applescript:

> Traceback (most recent call last):
>   File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 574, in run_
>     return self.run(edit)
>   File "/Users/homedir/Library/Application Support/Sublime Text 3/Packages/SendREPL/send_repl.py", line 67, in run
>     sender.send_text(cmd)
>   File "/Users/homedir/Library/Application Support/Sublime Text 3/Packages/SendREPL/text_sender.py", line 102, in send_text
>     super(RTextSender, self).send_text(cmd)
>   File "/Users/homedir/Library/Application Support/Sublime Text 3/Packages/SendREPL/text_sender.py", line 71, in send_text
>     self.send_to_iterm(cmd)
>   File "/Users/homedir/Library/Application Support/Sublime Text 3/Packages/SendREPL/text_sender.py", line 43, in send_to_iterm
>     send_to_iterm(cmd, self.bracketed_paste_mode)
>   File "/Users/homedir/Library/Application Support/Sublime Text 3/Packages/SendREPL/iterm/__init__.py", line 12, in send_to_iterm
>     osascript(ITERM, cmd)
>   File "/Users/homedir/Library/Application Support/Sublime Text 3/Packages/SendREPL/applescript/__init__.py", line 5, in osascript
>     subprocess.check_call(["osascript"] + list(args))
>   File "./subprocess.py", line 547, in check_call
>     
> subprocess.CalledProcessError: Command '['osascript', '/Users/homedir/Library/Application Support/Sublime Text 3/Packages/SendREPL/iterm/iterm.applescript', 'print("test")']' returned non-zero exit status 1
> 

In iTerm:
```shell
osascript "/Users/homedir/Library/Application Support/Sublime Text 3/Packages/SendREPL/iterm/iterm.applescript" 'print("test")'
```

gives

> /Users/homedir/Library/Application Support/Sublime Text 3/Packages/SendREPL/iterm/iterm.applescript:66:72: 
> script error: Expected end of line but found class name. (-2741)

**Comment by andrewrech** [comment]
Re-re-install fixed. Sorry. Thanks!
